apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-new-pvc
spec:
#  storageClassName: pv-demo
  volumeName: my-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
